# Generated by Django 5.1.4 on 2026-07-30 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('hire_request', 'Hire Request'), ('hire_accepted', 'Hire Accepted'), ('hire_rejected', 'Hire Rejected'), ('hire_completed', 'Hire Completed'), ('message', 'New Message'), ('review', 'New Review'), ('profile_view', 'Profile View'), ('system', 'System Announcement')], db_index=True, max_length=30)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional context data (e.g., hire_request_id, sender_id)')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='idx_notif_user'), models.Index(fields=['type', '-created_at'], name='idx_notif_type')],
            },
        ),
    ]
