# Generated by Django 5.1.4 on 2026-09-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
