# Generated by Django 5.1.4 on 2026-09-27 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_certificate_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shown_at', models.DateTimeField(auto_now_add=True)),
                ('shown_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shown_in_recommendations', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommendation History',
                'verbose_name_plural': 'Recommendation Histories',
                'db_table': 'recommendation_history',
                'indexes': [models.Index(fields=['viewer', 'shown_user'], name='recommendat_viewer__14cd80_idx'), models.Index(fields=['viewer', '-shown_at'], name='recommendat_viewer__449fe0_idx')],
            },
        ),
    ]
