# Generated by Django 5.1.4 on 2026-07-30 09:09

import django.db.models.deletion
import django.utils.timezone
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20, validators=[utils.validators.validate_phone_number])),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('bio', models.TextField(blank=True, default='', max_length=1000)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('github_url', models.URLField(blank=True, default='', validators=[utils.validators.validate_github_url])),
                ('linkedin_url', models.URLField(blank=True, default='', validators=[utils.validators.validate_linkedin_url])),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Default hourly rate in USD', max_digits=8, null=True)),
                ('languages', models.JSONField(blank=True, default=list, help_text='List of languages spoken, e.g. ["English", "Hindi"]')),
                ('availability', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], db_index=True, default='available', max_length=20)),
                ('is_admin', models.BooleanField(db_index=True, default=False, help_text='Designates whether this user has admin/moderator privileges.')),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Designates whether this user has verified their email.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10)),
                ('purpose', models.CharField(choices=[('email_verification', 'Email Verification'), ('password_reset', 'Password Reset')], max_length=30)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Code',
                'verbose_name_plural': 'OTP Codes',
                'db_table': 'otp_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_user_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified', 'is_active'], name='idx_user_status'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['availability'], name='idx_user_availability'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['location'], name='idx_user_location'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['user', 'purpose', 'is_used'], name='idx_otp_lookup'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['code', 'is_used'], name='idx_otp_code'),
        ),
    ]
