# Generated by Django 5.1.4 on 2026-09-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this user has verified their email.'),
        ),
        migrations.DeleteModel(
            name='OTPCode',
        ),
    ]
