# Generated by Django 5.1.4 on 2026-09-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_is_verified_delete_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_embedding',
            field=models.JSONField(blank=True, help_text='AI sentence embedding of user profile text (skills, bio, experience)', null=True),
        ),
    ]
