# Generated by Django 5.1.4 on 2026-07-30 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookmarked_user', models.ForeignKey(help_text='The user whose profile was bookmarked', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user who created the bookmark', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'db_table': 'bookmarks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_bookmark_user')],
                'unique_together': {('user', 'bookmarked_user')},
            },
        ),
    ]
