# Generated by Django 5.1.4 on 2026-07-30 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HireRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment URLs')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(help_text='The user who is hiring', on_delete=django.db.models.deletion.CASCADE, related_name='sent_hire_requests', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(help_text='The user being hired', on_delete=django.db.models.deletion.CASCADE, related_name='received_hire_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hire Request',
                'verbose_name_plural': 'Hire Requests',
                'db_table': 'hire_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'status'], name='idx_hire_client'), models.Index(fields=['provider', 'status'], name='idx_hire_provider'), models.Index(fields=['status', '-created_at'], name='idx_hire_status')],
            },
        ),
    ]
