# Generated by Django 5.1.4 on 2026-09-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirerequest',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
